#!/bin/bash

cat << EOF >> /etc/apt/sources.list.d/open-xchange.list

deb http://software.open-xchange.com/products/appsuite/stable/appsuiteui/DebianWheezy/ /
deb http://software.open-xchange.com/products/appsuite/stable/backend/DebianWheezy/ /

deb http://software.open-xchange.com/products/appsuite/stable/office/DebianWheezy /
deb http://software.open-xchange.com/products/appsuite/stable/office-web/DebianWheezy /
deb http://software.open-xchange.com/products/appsuite/stable/documentconverter-api/DebianWheezy /
deb http://software.open-xchange.com/products/appsuite/stable/calcengine/DebianWheezy/ /

# if you have a valid maintenance subscription, please uncomment the 
# following and add the ldb account data to the url so that the most recent
# packages get installed
# deb http://LDBACCOUNT:LDBPASSWORD@software.open-xchange.com/products/appsuite/stable/appsuiteui/updates/DebianWheezy /
# deb http://LDBACCOUNT:LDBPASSWORD@software.open-xchange.com/products/appsuite/stable/backend/updates/DebianWheezy /
# deb https://LDBACCOUNT:LDBPASSWORD@software.open-xchange.com/products/appsuite/stable/documentconverter-api/updates/DebianWheezy/ /

EOF

#mkdir -p /data/mysql
#ln -s /data/mysql /var/lib/mysql

apt-get update -y --force-yes
apt-get upgrade -y --force-yes

apt-get install -y --force-yes open-xchange open-xchange-authentication-database \
  open-xchange-grizzly open-xchange-admin open-xchange-appsuite open-xchange-appsuite-backend open-xchange-appsuite-manifest \
  open-xchange-appsuite-l10n-de-de open-xchange-appsuite-l10n-en-us \
  open-xchange-caldav open-xchange-carddav open-xchange-webdav-directory \
  open-xchange-drive open-xchange-drive-comet \
  open-xchange-eas-provisioning-mail \
  open-xchange-freebusy \
  open-xchange-mailfilter open-xchange-messaging  \
  open-xchange-mobile-config \
  open-xchange-passwordchange-database open-xchange-passwordchange-servlet \
  open-xchange-push-imapidle open-xchange-push-mailnotify \
  open-xchange-documentconverter-api calcengine open-xchange-documents-backend open-xchange-documents-ui open-xchange-documents-ui-static \
  hunspell hunspell-de-de hunspell-en-us \
  paxctl netcat mysql-server

apt-get upgrade -y --force-yes

echo PATH=$PATH:/opt/open-xchange/sbin/ >> ~/.bashrc && . ~/.bashrc

paxctl -Cm /usr/bin/java

chmod +x /ox.sh

a2enmod proxy proxy_http proxy_balancer expires deflate headers rewrite mime setenvif lbmethod_byrequests
a2enconf proxy_http

mv /etc/apache2/sites-available/000-default.new.conf /etc/apache2/sites-available/000-default.conf
mv /scripts/ox-etc/* /opt/open-xchange/etc/

